/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author UTSAV JAIN
 */
public class GameSetup extends javax.swing.JFrame {
    public static String firstPlayer;
    public static String secondPlayer;
    public static boolean firstCrossState;
    public static boolean firstZeroState;
    public static boolean secondCrossState;
    public static boolean secondZeroState;
   

    /**
     * Creates new form GameSetup
     */
    public GameSetup() {
        initComponents();
        firstPlayer="";
        secondPlayer="";
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameSetupPannel = new javax.swing.JPanel();
        gameSetupLabel = new javax.swing.JLabel();
        player1 = new javax.swing.JTextField();
        player2 = new javax.swing.JTextField();
        firstCross = new javax.swing.JRadioButton();
        firstZero = new javax.swing.JRadioButton();
        secondZero = new javax.swing.JRadioButton();
        secondCross = new javax.swing.JRadioButton();
        exitbt = new javax.swing.JButton();
        chooseMarkerLabel = new javax.swing.JLabel();
        playbt = new javax.swing.JButton();
        player1Label = new javax.swing.JLabel();
        player2Label = new javax.swing.JLabel();
        enterPlayer1 = new javax.swing.JButton();
        enterPlayer2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        gameSetupLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gameSetupLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameSetupLabel.setText("GAME SETUP");

        player1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        player2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        firstCross.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstCross.setText("X");
        firstCross.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstCrossActionPerformed(evt);
            }
        });

        firstZero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstZero.setText("O");
        firstZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstZeroActionPerformed(evt);
            }
        });

        secondZero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        secondZero.setText("O");
        secondZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondZeroActionPerformed(evt);
            }
        });

        secondCross.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        secondCross.setText("X");
        secondCross.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondCrossActionPerformed(evt);
            }
        });

        exitbt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitbt.setText("EXIT");
        exitbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtActionPerformed(evt);
            }
        });

        chooseMarkerLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chooseMarkerLabel.setText("(Choose marker)");

        playbt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        playbt.setText("PLAY");
        playbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playbtActionPerformed(evt);
            }
        });

        player1Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        player1Label.setText("First Player (Press Enter)");

        player2Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        player2Label.setText("Second Player (Press Enter)");

        enterPlayer1.setText("Enter");
        enterPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterPlayer1ActionPerformed(evt);
            }
        });

        enterPlayer2.setText("Enter");
        enterPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterPlayer2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gameSetupPannelLayout = new javax.swing.GroupLayout(gameSetupPannel);
        gameSetupPannel.setLayout(gameSetupPannelLayout);
        gameSetupPannelLayout.setHorizontalGroup(
            gameSetupPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameSetupPannelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(gameSetupPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameSetupPannelLayout.createSequentialGroup()
                        .addComponent(player1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(firstCross))
                    .addComponent(player1Label)
                    .addComponent(player2Label)
                    .addGroup(gameSetupPannelLayout.createSequentialGroup()
                        .addGroup(gameSetupPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(player2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(gameSetupPannelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(exitbt))
                            .addComponent(enterPlayer1)
                            .addComponent(enterPlayer2))
                        .addGroup(gameSetupPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gameSetupPannelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(playbt))
                            .addGroup(gameSetupPannelLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(gameSetupPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(firstZero)
                                    .addGroup(gameSetupPannelLayout.createSequentialGroup()
                                        .addComponent(secondZero)
                                        .addGap(61, 61, 61)
                                        .addComponent(secondCross))
                                    .addGroup(gameSetupPannelLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(chooseMarkerLabel)))))))
                .addGap(26, 26, 26))
            .addGroup(gameSetupPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameSetupLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        gameSetupPannelLayout.setVerticalGroup(
            gameSetupPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameSetupPannelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(gameSetupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(gameSetupPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1Label)
                    .addComponent(chooseMarkerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(gameSetupPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstZero)
                    .addComponent(firstCross))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterPlayer1)
                .addGap(41, 41, 41)
                .addComponent(player2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gameSetupPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondZero)
                    .addComponent(secondCross))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterPlayer2)
                .addGap(18, 25, Short.MAX_VALUE)
                .addGroup(gameSetupPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exitbt, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(playbt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameSetupPannel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameSetupPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playbtActionPerformed
        // TODO add your handling code here:
        int flag=0;
        if(!(firstZeroState)&&!(firstCrossState))
        {
            JOptionPane.showMessageDialog(null," Please select marker to start playing !");
            flag++;
        }
        if(player1.getText().equals(""))
        {   flag++;
            JOptionPane.showMessageDialog(null," Please Enter Player 1 name to start playing |");
        }
        if(player2.getText().equals(""))
        {   flag++;
            JOptionPane.showMessageDialog(null," Please Enter Player 2 name to start playing ! ");
        }
        if(flag==0)
        {
        this.setVisible(false);
        GameWindow gameFrame=new GameWindow();
        gameFrame.setVisible(true);
        }
        
        
    }//GEN-LAST:event_playbtActionPerformed

    private void exitbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtActionPerformed
        // TODO add your handling code here:
        int confirmExit=JOptionPane.showConfirmDialog(null, "Are you sure you want to Exit the game", "Continue?", 0);
        if(confirmExit==JOptionPane.YES_OPTION) 
                    dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        else
                    dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_OPENED));

           
    }//GEN-LAST:event_exitbtActionPerformed

    private void secondCrossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondCrossActionPerformed
        // TODO add your handling code here:
        if(secondCross.isSelected())
        {  firstZero.setSelected(true);
            secondZero.setSelected(false);
            firstCross.setSelected(false);
            setState(true,false,false,true);

        }
        else
        {
            firstZero.setSelected(false);
            secondZero.setSelected(false);
            firstCross.setSelected(false);
            setState(false,false,false,false);

        }
    }//GEN-LAST:event_secondCrossActionPerformed

    private void secondZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondZeroActionPerformed
        // TODO add your handling code here:
        if(secondZero.isSelected())
        {
            firstCross.setSelected(true);
            firstZero.setSelected(false);
            secondCross.setSelected(false);
            setState(false,true,true,false);
        }
        else
        {
            firstCross.setSelected(false);
            firstZero.setSelected(false);
            secondCross.setSelected(false);
            setState(false,false,false,false);
        }

    }//GEN-LAST:event_secondZeroActionPerformed

    private void firstZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstZeroActionPerformed
        // TODO add your handling code here:
        if(firstZero.isSelected())
        {
            secondCross.setSelected(true);
            secondZero.setSelected(false);
            firstCross.setSelected(false);
            setState(true,false,false,true);
        }
        else
        {
            secondCross.setSelected(false);
            secondZero.setSelected(false);
            firstCross.setSelected(false);
            setState(false,false,false,false);
        }
    }//GEN-LAST:event_firstZeroActionPerformed

    private void firstCrossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstCrossActionPerformed
        // TODO add your handling code here:
        if(firstCross.isSelected())
        {
            secondZero.setSelected(true);
            secondCross.setSelected(false);
            firstZero.setSelected(false);
            setState(false,true,true,false);
        }
        else
        {
            secondZero.setSelected(false);
            secondCross.setSelected(false);
            firstZero.setSelected(false);
            setState(false,false,false,false);
        }
    }//GEN-LAST:event_firstCrossActionPerformed

    private void enterPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterPlayer1ActionPerformed
        // TODO add your handling code here:
        if(player1.getText().equals(secondPlayer))
             JOptionPane.showMessageDialog(null, secondPlayer +" Already in use ! "+ " Please Select a different Name ");
        firstPlayer=player1.getText();
                
    }//GEN-LAST:event_enterPlayer1ActionPerformed

    private void enterPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterPlayer2ActionPerformed
        // TODO add your handling code here:
         if(player2.getText().equals(firstPlayer))
             JOptionPane.showMessageDialog(null,firstPlayer+" Already in use ! "+ " Please select different Name ");
        secondPlayer=player2.getText();
        
    }//GEN-LAST:event_enterPlayer2ActionPerformed
    private void setState(boolean fZero,boolean fCross,boolean sZero,boolean sCross)
    {
        firstZeroState=fZero;
        firstCrossState=fCross;
        secondZeroState=sZero;
        secondCrossState=sCross;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameSetup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chooseMarkerLabel;
    private javax.swing.JButton enterPlayer1;
    private javax.swing.JButton enterPlayer2;
    private javax.swing.JButton exitbt;
    private javax.swing.JRadioButton firstCross;
    private javax.swing.JRadioButton firstZero;
    private javax.swing.JLabel gameSetupLabel;
    private javax.swing.JPanel gameSetupPannel;
    private javax.swing.JButton playbt;
    private javax.swing.JTextField player1;
    private javax.swing.JLabel player1Label;
    private javax.swing.JTextField player2;
    private javax.swing.JLabel player2Label;
    private javax.swing.JRadioButton secondCross;
    private javax.swing.JRadioButton secondZero;
    // End of variables declaration//GEN-END:variables
}
